# Generated by Django 2.0.7 on 2018-07-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Imagenes_url', models.URLField()),
                ('Imagenes_name', models.CharField(max_length=200)),
                ('Imagenes_data', models.DateTimeField()),
            ],
            options={
                'db_table': 'Imagenes',
            },
        ),
    ]
