# Generated by Django 2.0.7 on 2018-07-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Comment_text', models.TextField(verbose_name='Коментарий')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_url', models.URLField()),
                ('Video_name', models.CharField(max_length=200)),
                ('Video_o', models.TextField(max_length=20)),
                ('Video_data', models.DateTimeField()),
                ('Video_likes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Video',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='Comment_Video',
            field=models.ForeignKey(on_delete=True, to='video.Video'),
        ),
    ]
